function [com] = pop_plotparticipantsaschannels(ALLERP)
    if isempty(ALLERP)
        disp('Error in pop_plotparticipantsaschannels(): This function cannot run on an empty ALLERP dataset.')
        beep
    else
        temptimes = [ALLERP.times];
        listch = {ALLERP(1).chanlocs.labels};
        for cT = 1:size(ALLERP,2)
          listch = unique(horzcat(listch, {ALLERP(cT).chanlocs.labels}));  
        end
        listch = sort(listch);
        origlistch = listch;
        for ch =1:numel(listch)
            listch{ch} = [num2str(ch) ' = ' listch{ch} ];
        end

        g1 = [ 0.5 0.5 ];
        s1 = [1];
        geometry = { g1 s1 g1 s1 g1 s1 g1 s1 s1 s1 s1 s1 };
        uilist = { ...
              { 'Style', 'text', 'string', 'Select Channel(s)'} ...
              { 'Style', 'popupmenu', 'string', listch 'tag' 'Channels' } ...
              ...
              { } ...
              ...
              { 'Style', 'text', 'string', 'ERP Bin'} ...
              { 'Style', 'edit', 'string', '1' 'tag' 'Bin' } ...
              ...
              { } ...
              ...
              { 'Style', 'text', 'string', 'X Axis Limits'} ...
              { 'Style', 'edit', 'string', sprintf('[%d %d]', min(temptimes), max(temptimes)) 'tag' 'XScale' } ...
              ...
              { } ...
              ...
              { 'Style', 'text', 'string', 'Plot Polarity'  } ...
              { 'Style', 'popupmenu', 'string', 'Positive Down | Positive Up' 'tag' 'Polarity' } ...
              ...
              { } ...
              ...
              { 'Style', 'text', 'string', 'Arrow Up and Down scale the amplitude.' } ...
              ...
              { 'Style', 'text', 'string', 'Holding shift while using the up and down arrow will linearly shift' } ...
              ...
              { 'Style', 'text', 'string', 'the axis up or down.' } ...
              ...
              { } ...
              ...
          };

          [ tmp1 tmp2 strhalt structout ] = inputgui( geometry, uilist, 'pophelp(''plotparticipantsaschannels'');', 'Comparison of ERP Activity -- pop_plotparticipantsaschannels');
          if ~isempty(structout)
              structout.Bin = str2num(structout.Bin);
              if (structout.Polarity == 1)
                  structout.Polarity = 'Positive Down';
              else
                  structout.Polarity = 'Positive Up';
              end
              structout.Channels = origlistch(structout.Channels);
              com = sprintf('\n%%Equivalent command:\n plotparticipantsaschannels(''Averages'', ALLERP, ''Bin'', %d, ''Channels'', {''%s''}, ''XScale'', %s, ''Polarity'', ''%s'');\n', structout.Bin, cell2mat(structout.Channels), structout.XScale, structout.Polarity);
              disp(com)
              plotparticipantsaschannels('Averages', ALLERP, 'Bin', structout.Bin, 'Channels', structout.Channels, 'XScale', str2num(structout.XScale), 'Polarity', structout.Polarity);
          else
              com = '';
          end
    end
end