function [OUTEEG, com] = pop_visualinspectarray(INEEG)

    g1 = [0.5 0.5 ];
    s1 = [1];
    geometry = { g1 s1 g1 s1 g1 s1 g1 s1 g1 s1 s1 s1 s1 s1 s1 s1 s1 };
    uilist = { ...
          { 'Style', 'text', 'string', 'Display ERP Average'} ...
          { 'Style', 'popupmenu', 'string', 'True | False' 'tag' 'Average' } ...
          ...
          { } ...
          ...
          { 'Style', 'text', 'string', 'Plot Polarity'  } ...
          { 'Style', 'popupmenu', 'string', 'Positive Down | Positive Up' 'tag' 'Polarity' } ...
          ...
          { } ...
          ...
          { 'Style', 'text', 'string', 'Display Axis on Channel'  } ...
          { 'Style', 'edit', 'string', 'M1' 'tag' 'ChannelScale' } ...
          ...
          { } ...
          ...
          { 'Style', 'text', 'string', 'Smooth Data'  } ...
          { 'Style', 'popupmenu', 'string', 'False | True' 'tag' 'Smooth' } ...
          ...
          { } ...
          ...
          { 'Style', 'text', 'string', 'Font Size' } ...
          { 'Style', 'edit', 'string', '8' 'tag' 'guiFontSize' } ...
          ...
          { } ...
          ...
          { 'Style', 'text', 'string', 'To reject a trial click ''d''. Rejected trials will have a red background.' } ...
          ...
          { 'Style', 'text', 'string', 'To accept a trial click ''c''.' } ...
          ...
          { 'Style', 'text', 'string', 'Arrow Left and Right can be used to scroll through the data.' } ...
          ...
          { 'Style', 'text', 'string', 'Arrow Up and Down scale the amplitude.' } ...
          ...
          { 'Style', 'text', 'string', 'Holding shift while using the up and down arrow will linearly shift' } ...
          ...
          { 'Style', 'text', 'string', 'the axis up or down.' } ...
          ...
          { } ...
          ...
      };
 
      [ tmp1 tmp2 strhalt structout ] = inputgui( geometry, uilist, 'pophelp(''pop_visualinspectarray'');', 'Visually Inspect EEG Array -- pop_visualinspectarray');
      if ~isempty(structout)
          if (structout.Polarity == 1)
              structout.Polarity = 'Positive Down';
          else
              structout.Polarity = 'Positive Up';
          end
          if (structout.Average == 1)
              structout.Average = 'True';
          else
              structout.Average = 'False';
          end
          if (structout.Smooth == 1)
              structout.Smooth = 'False';
          else
              structout.Smooth = 'True';
          end
          com = sprintf('\nRunning:\n\t%s = visualinspectarray(%s, ''ChannelScale'', ''%s'', ''Polarity'', ''%s'', ''Average'', ''%s'', ''Smooth'', ''%s'');\n', inputname(1), inputname(1), structout.ChannelScale, structout.Polarity, structout.Average, structout.Smooth);
          disp(com)
          
          [T, INEEG] = evalc('pop_syncroartifacts(INEEG, ''Direction'', ''bidirectional'')'); %synchronize artifact databases
          OUTEEG = visualinspectarray(INEEG, 'ChannelScale', structout.ChannelScale, 'Polarity', structout.Polarity, 'Average', structout.Average, 'Smooth', structout.Smooth);
          disp('Updated EEG.reject.rejmanual.')
          [T, OUTEEG] = evalc('pop_syncroartifacts(OUTEEG, ''Direction'', ''eeglab2erplab'')'); %synchronize artifact databases
      else
          OUTEEG = INEEG;
          com = '';
      end

end